# Schema for the configuration files of the TVI module.
tvi.global_settings:
  type: config_object
  label: 'TVI settings'
  mapping:
    disable_default_view:
      type: boolean
      label: 'Disable Default View'
    enable_override:
      type: boolean
      label: 'Override View for all entities'
    view:
      type: string
      label: 'View ID'
    view_display:
      type: string
      label: 'View Display ID'

tvi.taxonomy_term.*:
  type: config_object
  label: 'TVI Term settings'
  mapping:
    enable_override:
      type: boolean
      label: 'Override View for all entities'
    view:
      type: string
      label: 'View ID'
    view_display:
      type: string
      label: 'View Display ID'
    inherit_settings:
      type: boolean
      label: 'Children should Inheirt Settings'
    pass_arguments:
      type: boolean
      label: 'Pass Arguements to view'

tvi.taxonomy_vocabulary.*:
  type: config_object
  label: 'TVI Vocabulary settings'
  mapping:
    enable_override:
      type: boolean
      label: 'Override View for all entities'
    view:
      type: string
      label: 'View ID'
    view_display:
      type: string
      label: 'View Display ID'
    inherit_settings:
      type: boolean
      label: 'Children should Inheirt Settings'
    pass_arguments:
      type: boolean
      label: 'Pass Arguements to view'
